package com.atech.financialapp.ui.theme

import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF2AE881)
val surfaceLight = Color(0xFFF3EDF7)
val onSurfaceVariantLight = Color(0xFFEFFAFF)
val onSurfaceLight = Color(0xFFFEF7FF)
val inverseOnSurfaceLight = Color(0xFF1D1B20)
val outlineLight = Color(0xFFD3FAE6)
val surfaceTintLight = Color(0xFF29E881)
val surfaceContainerLight = Color(0xFF49454F)
val surfaceContainerLowLight = Color(0xFFD4FAE6)
val surfaceDimLight = Color(0xFFCAC4D0)
val primaryContainerLight = Color(0xFFECE6F0)
val inverseSurfaceLight = Color(0xFF3D3D3D)
val secondaryContainerLight = Color(0xFF7C7681)
val onSecondaryLight = Color(0xFFE9E5EC)
val tertiaryContainerLight = Color(0xFFE46962)

val primaryDark = Color(0xFF2AE881)
val surfaceDark = Color(0xFFF3EDF7)
val onSurfaceVariantDark = Color(0xFFEFFAFF)
val onSurfaceDark = Color(0xFFFEF7FF)
val inverseOnSurfaceDark = Color(0xFF1D1B20)
val outlineDark = Color(0xFFD4FAE6)
val surfaceTintDark = Color(0xFF29E881)
val surfaceContainerDark = Color(0xFF49454F)
val surfaceContainerLowDark = Color(0xFFD4FAE6)
val surfaceDimDark = Color(0xFFCAC4D0)
val primaryContainerDark = Color(0xFFECE6F0)
val inverseSurfaceDark = Color(0xFF3D3D3D)
val secondaryContainerDark = Color(0xFF7C7681)
val onSecondaryDark = Color(0xFFE9E5EC)
val tertiaryContainerDark = Color(0xFFE46962)